/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/UI/Alert.vue')['default']
    Badge: typeof import('./src/components/UI/Badge.vue')['default']
    Button: typeof import('./src/components/UI/Button.vue')['default']
    Card: typeof import('./src/components/UI/Card.vue')['default']
    Checkbox: typeof import('./src/components/UI/Checkbox.vue')['default']
    FormFieldWrapper: typeof import('./src/components/UI/FormFieldWrapper.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconInput: typeof import('./src/components/UI/IconInput.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Input: typeof import('./src/components/UI/Input.vue')['default']
    LiveSearchBar: typeof import('./src/components/UI/LiveSearchBar.vue')['default']
    MenuItems: typeof import('./src/components/menuDetail/MenuItems.vue')['default']
    MenusView: typeof import('./src/components/homepage/MenusView.vue')['default']
    Modal: typeof import('./src/components/UI/Modal.vue')['default']
    MultiSelect: typeof import('./src/components/UI/MultiSelect.vue')['default']
    Navbar: typeof import('./src/components/UI/Navbar.vue')['default']
    ProductsView: typeof import('./src/components/homepage/ProductsView.vue')['default']
    ProgressBar: typeof import('./src/components/UI/ProgressBar.vue')['default']
    Resumen: typeof import('./src/components/menuDetail/Resumen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/UI/SectionHeader.vue')['default']
    Select: typeof import('./src/components/UI/Select.vue')['default']
    Table: typeof import('./src/components/UI/Table.vue')['default']
    Tabs: typeof import('./src/components/UI/Tabs.vue')['default']
    Textarea: typeof import('./src/components/UI/Textarea.vue')['default']
  }
}
